### ISSUE TITLE
Colour selector looks strange in Materialize

### ISSUE THREAD

**Issue by gezakerecsenyi** [codeddraig/ffau#12]
Materialize seems to have overridden the styling for colour selectors, spacing them out massively. They still technically work, but they are difficult to use.

![image](https://user-images.githubusercontent.com/32415108/34462966-beaea420-ee46-11e7-87e2-07405e91b5c0.png)

**Comment by tti0** [comment]
Not an issue. See comment from @palkerecsenyi on WhatsApp.

**Comment by tti0** [comment]
As pointed out by @gezakerecsenyi yesterday, this is an issue, which will be resolved in interim release 0.1.3. I will begin work now.

**Comment by tti0** [comment]
Actually, this might be harder to fix than thought, as the colour grid is generated outside of Blockly. Will investigate for 0.2.0.
