### ISSUE TITLE
Fix bugs in scripting

### ISSUE THREAD

**Issue by palkerecsenyi** [codeddraig/ffau#19]
This is quite complicated. In the scripting branch, basic JS functionality has been added, which generates masses of strange browser errors, exactly like https://github.com/bwinf/blockly-html. Many JS elements fail to generate any code at all, but others work perfectly.
![image](https://user-images.githubusercontent.com/22198767/34470936-14eb0430-ef34-11e7-9283-4d652ffa6774.png)
Demo available at http://cdbeta.hma-uk.org/create/editor/google/?project=111

**Comment by tti0** [comment]
Issue closed temporarily, as 0.2.0 dev cycle has not begun.

**Comment by tti0** [comment]
Issue reopened - 0.2.0 development cycle has begun.

**Comment by tti0** [comment]
Closed temporarily - this feature will now be implemented in 0.3.0 dev cycle.
