### ISSUE TITLE
Add CSS Tags for 0.2.0

### ISSUE THREAD

**Issue by palkerecsenyi** [codeddraig/ffau#20]
0.2.0 will introduce many CSS items to make it easier to style blocks. This is a list of all planned additions (roughly grouped):

- background-image
- background-position
- background-repeat
- background-size
---
- border-radius
---
- box-shadow
- text-shadow
---
- cursor
---
- display
- overflow
- padding
---
- list-style
---
- max-height
- max-width
- min-height
- min-width
---
- opacity
- visibility
---
- text-align
- text-decoration
---
- vertical-align
- z-index

As well as CSS event selectors (e.g. :hover :focus ::after ::before)

**Comment by tti0** [comment]
Yes, I agree with the above changes. Approved for implementation in 0.2.0.

**Comment by palkerecsenyi** [comment]
Added events (e.g. :hover :focus)

**Comment by palkerecsenyi** [comment]
Added :not() selector

**Comment by palkerecsenyi** [comment]
Added bgimage

**Comment by palkerecsenyi** [comment]
Added bgposition

**Comment by tti0** [comment]
Changes resolved in issue #32 .
