### ISSUE TITLE
Add <video> tag

### ISSUE THREAD

**Issue by tti0** [codeddraig/ffau#21]
This work is to take place straight away, as video tags are a key feature of HTML5. For the video sources, please look to the following links:

http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4

https://drive.google.com/open?id=1zpd4ffvtGw7ZHBTZG5ZtnR5PH5wN74zh

Both are open films from the Blender Foundation. The first is Big Buck Bunny (approx. length 10 mins), in 1080p, 30fps, MP4. The second is an animated short made by the Blender Foundation called "Llama Drama", set in Peru, involving a relatively stupid llama attempting to cross a road in a humorous fashion... It is approx. 2 mins in length, 1080p, 30fps.

Both links are CDN, as requested. Both have sound, and are MP4s. Even though the HTML5 standard allows OGG video, I have never seen this used in the wild, so stuck to MP4.

Thanks, @tti0!

**Comment by palkerecsenyi** [comment]
I'll add the video tag in a similar way to audio.

**Comment by palkerecsenyi** [comment]
See #22
