### ISSUE TITLE
Scripting problems

### ISSUE THREAD

**Issue by tti0** [codeddraig/ffau#42]
![image](https://user-images.githubusercontent.com/14841064/37255526-a862c436-2545-11e8-8485-4e14fd28ed99.png)
As seen above, when JS is added to a project, it is not updated in Ace, and this red 'X' icon appears (Ace line 8), which displays the text 

>Unexpected start tag token (script) in the after body phase.

After this, no new blocks added will update in the Real code or Preview tabs. I think that we need to change the nesting settings for script blocks, as Ace just seems to crash after a syntax error.

**Comment by tti0** [comment]
*N.B. Issue tested on Ubuntu Linux 16.04, Chromium version 64.0.3282.167**

**Comment by palkerecsenyi** [comment]
Interesting. Similar issue used to happen on CDR, but was fixed. Can't identify same source of issue. Problem isn't with Ace - Ace is complaining about the non-semantic location of the script tag, which is a simple issue to do with where Blockly let's you put the script tag (changeable easily). Bigger issue is the `repeat` not working.

When I had this issue on CDR, I managed to narrow it down to the Math number inputs not working. Could you please see if this is the case here as well? Please have your browser's JS console open while testing. Thanks.

**Comment by tti0** [comment]
Please see Chromium's JS console log here:
https://gist.github.com/tti0/30f3a956db2672075583c86b09ff8343

**Comment by palkerecsenyi** [comment]
Issue mainly fixed in 4283119 using `Blockly.JavaScript.init(workspace)`.
