### ISSUE TITLE
<!DOCTYPE html> and Ace

### ISSUE THREAD

**Issue by tti0** [codeddraig/ffau#43]
![image](https://user-images.githubusercontent.com/14841064/37255594-6174ab10-2546-11e8-8e29-b2e174153462.png)

A follow on from bug report #42, however more to do with Ace. We need to add that `<!DOCTYPE html>` is automatically included at the start of text output, although it does not need to appear in the blocks. It is good practice to do this in website design, and relevant notes will appear in the docs.

Note the 'i' icon next to line 1 in Ace. Upon hover, we get

>Start tag seen without seeing a doctype first. Expected e.g. <!DOCTYPE html>.

*N.B. Issue tested on Ubuntu Linux 16.04, Chromium version 64.0.3282.167*

**Comment by palkerecsenyi** [comment]
Will fix. Indeed, we are encouraging bad practice! I'll make a `!DOCTYPE html` appear magically with the `html` block.

**Comment by palkerecsenyi** [comment]
Fixed in 317d259
