### ISSUE TITLE
JavaScript: Add console box

### ISSUE THREAD

**Issue by tti0** [codeddraig/ffau#45]
Add a console box to the Ffau editor, where printouts from command console.log will be displayed.

**Comment by palkerecsenyi** [comment]
This would break the security barrier between an iframe and the window, which most browsers disallow. We are unable to watch the console directly and log things to a console. However, we can log to the browser console, which can be opened by pressing F12.  This will show regular `console.log` operations as per normal, even from within the iframe.

**Comment by tti0** [comment]
Yes, we should do this, and prefix all real log outputs with `Ffau Editor Log: `.

**Comment by palkerecsenyi** [comment]
Ok, I'll implement this

**Comment by palkerecsenyi** [comment]
Should be fixed in ec263ea
