### ISSUE TITLE
Add block <button>

### ISSUE THREAD

**Issue by tti0** [codeddraig/ffau#50]
Please can we add a block for the `<button>` tag for 0.3.1(a).

**Comment by palkerecsenyi** [comment]
Of course. Closest current alternative is `<input type="submit">`, which can (in some instances) be styled to work like a button. Most CSS frameworks can also apply button styles to `<a>` tags, so those are a current alternative too. E.g. in Magic, you can add a `btn btn-default` class to an `<a>` tag to make it look like a button.

Despite, this I will add the button ASAP.

**Comment by palkerecsenyi** [comment]
Should be fixed in #51
