### ISSUE TITLE
text-shadow block is escaped, including "#" in hex colour

### ISSUE THREAD

**Issue by gezakerecsenyi** [codeddraig/ffau#58]
When using the text-shadow block, the "#" in the shadow-colour attribute is escaped to `%23`, making the block unusable as the default colour is overridden, but by an invalid attribute.
![image](https://user-images.githubusercontent.com/32415108/46906928-cf52e280-cf02-11e8-8b4a-fbe02ae0c3c2.png)
becomes
![image](https://user-images.githubusercontent.com/32415108/46906937-f0b3ce80-cf02-11e8-97e4-fb757d0080b8.png)

**Comment by palkerecsenyi** [comment]
This has been fixed in Ffau 1.0.0
