### ISSUE TITLE
Create subsection of Style > Items > Design for Borders

### ISSUE THREAD

**Issue by gezakerecsenyi** [codeddraig/ffau#61]
Create new 'Borders' section under Style > Items > Design to fit all items in #62

**Comment by palkerecsenyi** [comment]
I don't think we should make a subsection under Design, because that would be 4 levels of nesting, which would be both very tight for space, and also very hard to fluidly navigate. Maybe we could just have Style > Items > Borders

**Comment by gezakerecsenyi** [comment]
OK. Move all blocks currently under Border in Style > Items > Design into there (e.g `border-radius`), as well as #62, #63, #64, #65

**Comment by palkerecsenyi** [comment]
Style > Items > Borders is now live with all border items moved inside it
