### ISSUE TITLE
Use block themeing via new Blockly Theme API

### ISSUE THREAD

**Issue by palkerecsenyi** [codeddraig/ffau#73]
Use the new Blockly Theme API to make a categorical and global styleset for colouring blocks, which is a lot neater than setting 3-digit proprietary Blockly colour code.

See [this](https://developers.google.com/blockly/guides/configure/web/themes) for more info.

Here's an example of how normal Blockly blocks can be styled with the Theme API:

### Blocks

```
{
   "list_blocks": {
      "colourPrimary": "#4a148c",
      "colourSecondary":"#AD7BE9",
      "colourTertiary":"#CDB6E9"
   },
   "logic_blocks": {
      "colourPrimary": "#01579b",
      "colourSecondary":"#64C7FF",
      "colourTertiary":"#C5EAFF"
   }
}
```

### Categories

```
{
   "list_category": {
      "colours": "#4a148c"
   },
   "logic_category": {
      "colour": "#01579b",
   }
}
```

```
<category name="Logic" style="logic_category">
</category>
```

```
"style":"logic_blocks"
```

It's fairly simple to put it all together:

```
var theme = Blockly.Theme(blockStyles, categoryStyles);
```

That's it!

**Comment by gezakerecsenyi** [comment]
Done with #81, but using custom methods (not Theme API)
